apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubeflow-registry-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi

