apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
  namespace: kubeflow-user-example-com
  annotations:
    autoscaling.knative.dev/min-scale: "0"
    autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "100m"
          memory: "256Mi"

